name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths:
      - final-project-folder/** #only trigers if files in this folder changes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Image
        run: docker build -t abdullahbutt01/devops-final:latest ./final-project-folder

      - name: Push Image
        run: docker push abdullahbutt01/devops-final:latest
